import Head from 'next/head'
import AddressTable from '../components/page/AddressTable'
import Footer from '../components/page/Footer'
import ProductTable from '../components/page/ProductTable'
import NumberInWord from '../components/page/NumberInWord'
import PayDetails from '../components/page/PayDetails'
import HeadSection from '../components/page/Head'
import {useDispatch, useSelector} from "react-redux"
import React,{useState, useEffect} from 'react'
import isEmpty from 'lodash/isEmpty'
import {SampleData,CGST,SGST} from "../utils/constants/app.constant"
import {totalAmount} from "../utils/utils-function"

export default function Page() 
{
  let pageData = useSelector((state)=>state.pageData)
  let roleList = useSelector((state)=>state.pageData.roles)

  const [data, setData] = useState(SampleData)
  const [AllRoles, setAllRoles] = useState(SampleData.roles)

  console.log(pageData);

  useEffect(() => {
    if(isEmpty(pageData.companyProfile))
    {
      setData(SampleData)
    }
    else{
      setData(pageData)
    }
  }, [pageData])

  useEffect(() => {
    if(isEmpty(roleList))
    {
      setAllRoles(data.roles)
    }else{
      setAllRoles(roleList)
    }
  }, [roleList])
  
  return (
    <>
      <Head>
        <title>Invoice Gen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isEmpty(data) ? 
      <div>
        Loading........
      </div> 
      :
      <>
      {AllRoles.map((element, idx)=>
      {
        let Numbervalue = totalAmount(data?.productInfo?.products, CGST,SGST)
        
        return  <div key={idx} className={`${idx === 0 ? "" : "mt-20"}`}>
        {/* title Role section */}
           <HeadSection role={element}/>
              <div className='border-solid border-2'  style={{borderLeft:"none", borderRight:"none",borderTop:"none"}} >
              {/* Address section */} 
            <AddressTable companyProfile={data.companyProfile} buyerProfile={data.buyerProfile} invoiceInfo={data.invoiceInfo}/>

            {/* product Table */}
            <ProductTable productList={data?.productInfo}/>

            {/* name section */}
            <NumberInWord totalPrice={Numbervalue} />

            {/* PayDetails*/}
            <PayDetails productList={data.productInfo}/>

            {/* Footer*/}
            <Footer productList={data.productInfo} extraInfo={data.extraInfo}/>
           </div>
           <div className='text-center w-full py-2 font-light text-xs'>
                This is a Computer Generated Invoice
          </div>
        </div>
      })}
     </>
     }
    </>
  )
}
